-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 09:26:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `IdUsuario` INT NOT NULL,
  `Usuario` VARCHAR(16) NOT NULL,
  `clave` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdUsuario`));


-- -----------------------------------------------------
-- Table `mydb`.`Salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salon` (
  `idSalon` INT NOT NULL,
  `NombreSalon` VARCHAR(45) NULL,
  `CantidadSalon` INT NULL,
  `CantidadSillas` INT NULL,
  `Nombredirector` VARCHAR(45) NULL,
  `Nombredirector2` VARCHAR(45) NULL,
  `Apellidodirector` VARCHAR(45) NULL,
  `Apellidodirector2` VARCHAR(45) NULL,
  PRIMARY KEY (`idSalon`));


-- -----------------------------------------------------
-- Table `mydb`.`IndoleActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IndoleActividad` (
  `idIndoleActividad` INT NOT NULL,
  `IndoleActividadcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idIndoleActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoActividad` (
  `idTipoActividad` INT NOT NULL,
  `TipoActividad` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FocusActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FocusActividad` (
  `idFocusActividad` INT NOT NULL,
  `FocusActividad` VARCHAR(45) NULL,
  PRIMARY KEY (`idFocusActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RequisitosActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RequisitosActividad` (
  `idRequisitosActividad` INT NOT NULL,
  `RequisitosActividad` VARCHAR(200) NULL,
  PRIMARY KEY (`idRequisitosActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actividad` (
  `idActividad` INT NOT NULL,
  `NombreActividad` VARCHAR(45) NULL,
  `FechaActividad` DATETIME NULL,
  `Participantes` INT NULL,
  `CantidadEncuentros` INT NULL,
  `HoraInicio` DATETIME NULL,
  `Nombre1` VARCHAR(45) NULL,
  `Nombre2` VARCHAR(45) NULL,
  `Apellido1` VARCHAR(45) NULL,
  `Apellido2` VARCHAR(45) NULL,
  `Telefono` INT NULL,
  `HoraCierre` DATETIME NULL,
  `Salon_idSalon` INT NOT NULL,
  `IndoleActividad_idIndoleActividad` INT NOT NULL,
  `RequisitosActividad_idRequisitosActividad` INT NOT NULL,
  `TipoActividad_idTipoActividad` INT NOT NULL,
  `FocusActividad_idFocusActividad` INT NOT NULL,
  `user_IdUsuario` INT NOT NULL,
  PRIMARY KEY (`idActividad`, `Salon_idSalon`, `IndoleActividad_idIndoleActividad`, `RequisitosActividad_idRequisitosActividad`, `TipoActividad_idTipoActividad`, `FocusActividad_idFocusActividad`, `user_IdUsuario`),
  INDEX `fk_Actividad_Salon1_idx` (`Salon_idSalon` ASC),
  INDEX `fk_Actividad_IndoleActividad1_idx` (`IndoleActividad_idIndoleActividad` ASC),
  INDEX `fk_Actividad_RequisitosActividad1_idx` (`RequisitosActividad_idRequisitosActividad` ASC),
  INDEX `fk_Actividad_TipoActividad1_idx` (`TipoActividad_idTipoActividad` ASC),
  INDEX `fk_Actividad_FocusActividad1_idx` (`FocusActividad_idFocusActividad` ASC),
  INDEX `fk_Actividad_user1_idx` (`user_IdUsuario` ASC),
  CONSTRAINT `fk_Actividad_Salon1`
    FOREIGN KEY (`Salon_idSalon`)
    REFERENCES `mydb`.`Salon` (`idSalon`),
  CONSTRAINT `fk_Actividad_IndoleActividad1`
    FOREIGN KEY (`IndoleActividad_idIndoleActividad`)
    REFERENCES `mydb`.`IndoleActividad` (`idIndoleActividad`),
  CONSTRAINT `fk_Actividad_RequisitosActividad1`
    FOREIGN KEY (`RequisitosActividad_idRequisitosActividad`)
    REFERENCES `mydb`.`RequisitosActividad` (`idRequisitosActividad`),
  CONSTRAINT `fk_Actividad_TipoActividad1`
    FOREIGN KEY (`TipoActividad_idTipoActividad`)
    REFERENCES `mydb`.`TipoActividad` (`idTipoActividad`),
  CONSTRAINT `fk_Actividad_FocusActividad1`
    FOREIGN KEY (`FocusActividad_idFocusActividad`)
    REFERENCES `mydb`.`FocusActividad` (`idFocusActividad`),
  CONSTRAINT `fk_Actividad_user1`
    FOREIGN KEY (`user_IdUsuario`)
    REFERENCES `mydb`.`user` (`IdUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
