-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 09:26:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `IdUsuario` INT NOT NULL,
  `privilegio` VARCHAR(10) NOT NULL,
  `Usuario` VARCHAR(16) NOT NULL,
  `clave` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`IdUsuario`));


-- -----------------------------------------------------
-- Table `mydb`.`Salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salon` (
  `idSalon` INT NOT NULL,
  `NombreSalon` VARCHAR(45) NULL,
  `CantidadPersonasSalon` INT NULL,
  `CantidadSillas` INT NULL,
  `Nombredirector` VARCHAR(45) NULL,
  `Nombredirector2` VARCHAR(45) NULL,
  `Apellidodirector` VARCHAR(45) NULL,
  `Apellidodirector2` VARCHAR(45) NULL,
  PRIMARY KEY (`idSalon`));


-- -----------------------------------------------------
-- Table `mydb`.`IndoleActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IndoleActividad` (
  `idIndoleActividad` INT NOT NULL,
  `IndoleActividadcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idIndoleActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoActividad` (
  `idTipoActividad` INT NOT NULL,
  `TipoActividad` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FocusActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FocusActividad` (
  `idFocusActividad` INT NOT NULL,
  `FocusActividad` VARCHAR(45) NULL,
  PRIMARY KEY (`idFocusActividad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RequisitosActividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RequisitosActividad` (
  `idRequisitosActividad` INT NOT NULL,
  `RequisitosActividad` VARCHAR(200) NULL,
  PRIMARY KEY (`idRequisitosActividad`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Nacionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nacionalidad` (
  `idNacionalidad` INT NOT NULL,
  `Nacionalidad` VARCHAR(1) NULL,
  PRIMARY KEY (`idNacionalidad`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Responsable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responsable` (
  `RCedula` INT NOT NULL,
  `Nombre1` VARCHAR(20) NULL,
  `Nombre2` VARCHAR(20) NULL,
  `Apellido1` VARCHAR(20) NULL,
  `Apellido2` VARCHAR(20) NULL,
  `Telefono` INT NULL,
  `Nacionalidad_idNacionalidad` INT NOT NULL,
  PRIMARY KEY (`RCedula`),
  INDEX `fk_responsable_Nacionalidad1_idx` (`Nacionalidad_idNacionalidad` ASC),
  CONSTRAINT `fk_responsable_Nacionalidad1` FOREIGN KEY (`Nacionalidad_idNacionalidad`) REFERENCES `mydb`.`Nacionalidad` (`idNacionalidad`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`Actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Actividad` (
  `idActividad` INT (11) AUTO_INCREMENT,
  `Estatus` VARCHAR(10) NULL,
  `NombreActividad` VARCHAR(45) NULL,
  `FechaActividad` DATE NULL,
  `Participantes` INT NULL,
  `CantidadEncuentros` INT NULL,
  `HoraInicio` TIME NULL,
  `HoraCierre` TIME NULL,
  `responsable_RCedula` INT NOT NULL,
  `Salon_idSalon` INT NOT NULL,
  `IndoleActividad_idIndoleActividad` INT NOT NULL,
  `RequisitosActividad_idRequisitosActividad` INT NOT NULL,
  `TipoActividad_idTipoActividad` INT NOT NULL,
  `FocusActividad_idFocusActividad` INT NOT NULL,
  `user_IdUsuario` INT NOT NULL,
  PRIMARY KEY (`idActividad`),
  INDEX `fk_Actividad_responsable1_idx` (`responsable_RCedula` ASC),
  INDEX `fk_Actividad_Salon1_idx` (`Salon_idSalon` ASC),
  CONSTRAINT `fk_Actividad_responsable1` FOREIGN KEY (`responsable_RCedula`) REFERENCES `mydb`.`responsable` (`RCedula`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_Actividad_Salon1` FOREIGN KEY (`Salon_idSalon`) REFERENCES `mydb`.`Salon` (`idSalon`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
